// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back.Data;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829180046_AddImportJobs")]
    partial class AddImportJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClaseUser", b =>
                {
                    b.Property<int>("ClasesEstudianteId")
                        .HasColumnType("integer");

                    b.Property<int>("EstudiantesId")
                        .HasColumnType("integer");

                    b.HasKey("ClasesEstudianteId", "EstudiantesId");

                    b.HasIndex("EstudiantesId");

                    b.ToTable("ClaseEstudiante", (string)null);
                });

            modelBuilder.Entity("back.Entities.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("back.Entities.ActividadAyudantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AyudantiaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Completada")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPlanificada")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AyudantiaId");

                    b.ToTable("ActividadesAyudantia");
                });

            modelBuilder.Entity("back.Entities.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseSesionId")
                        .HasColumnType("integer");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClaseSesionId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("back.Entities.Ayudantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatedraId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatedraId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Ayudantias");
                });

            modelBuilder.Entity("back.Entities.Bitacora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActividadesRealizadas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AyudantiaId")
                        .HasColumnType("integer");

                    b.Property<string>("EvidenciaUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AyudantiaId");

                    b.ToTable("Bitacoras");
                });

            modelBuilder.Entity("back.Entities.Catedra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<double?>("MinimoNota")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.ToTable("Catedras");
                });

            modelBuilder.Entity("back.Entities.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("MateriaId");

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("back.Entities.ClaseSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AplicacionVirtual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AulaPresencial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ClaseId")
                        .HasColumnType("integer");

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<string>("EdificioPresencial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<string>("LinkVirtual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<string>("PisoPresencial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoClase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("MateriaId");

                    b.ToTable("ClasesSesiones");
                });

            modelBuilder.Entity("back.Entities.CronogramaActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatedraId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPrevista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaReal")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatedraId");

                    b.ToTable("Cronogramas");
                });

            modelBuilder.Entity("back.Entities.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdaptadaConIA")
                        .HasColumnType("boolean");

                    b.Property<int>("CatedraId")
                        .HasColumnType("integer");

                    b.Property<string>("DescripcionIA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsDiagnostica")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatedraId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("back.Entities.ImportJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ImportJobs");
                });

            modelBuilder.Entity("back.Entities.ImportJobEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ImportJobId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId");

                    b.ToTable("ImportJobEntries");
                });

            modelBuilder.Entity("back.Entities.IndicadorCualitativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatedraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Indicador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatedraId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("IndicadoresCualitativos");
                });

            modelBuilder.Entity("back.Entities.Inscripcion", b =>
                {
                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<int>("CatedraId")
                        .HasColumnType("integer");

                    b.Property<bool>("AlertaRendimiento")
                        .HasColumnType("boolean");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<double>("PromedioActual")
                        .HasColumnType("double precision");

                    b.HasKey("EstudianteId", "CatedraId");

                    b.HasIndex("CatedraId");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("back.Entities.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocenteResponsableId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocenteResponsableId");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("back.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("back.Entities.Presentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AyudantiaId")
                        .HasColumnType("integer");

                    b.Property<int?>("CoordinadorCarreraId")
                        .HasColumnType("integer");

                    b.Property<int?>("DecanoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfesoresAsignados")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AyudantiaId");

                    b.HasIndex("CoordinadorCarreraId");

                    b.HasIndex("DecanoId");

                    b.ToTable("Presentaciones");
                });

            modelBuilder.Entity("back.Entities.PresentacionEvaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JuradoId")
                        .HasColumnType("integer");

                    b.Property<double>("Nota")
                        .HasColumnType("double precision");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PresentacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JuradoId");

                    b.HasIndex("PresentacionId");

                    b.ToTable("PresentacionEvaluaciones");
                });

            modelBuilder.Entity("back.Entities.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsEsencial")
                        .HasColumnType("boolean");

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("back.Entities.RecursoVistoPorEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVisto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("RecursoId");

                    b.ToTable("RecursosVistosPorEstudiante");
                });

            modelBuilder.Entity("back.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClaseUser", b =>
                {
                    b.HasOne("back.Entities.Clase", null)
                        .WithMany()
                        .HasForeignKey("ClasesEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("EstudiantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("back.Entities.Actividad", b =>
                {
                    b.HasOne("back.Entities.Materia", "Materia")
                        .WithMany("Actividades")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("back.Entities.ActividadAyudantia", b =>
                {
                    b.HasOne("back.Entities.Ayudantia", "Ayudantia")
                        .WithMany("Planificacion")
                        .HasForeignKey("AyudantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ayudantia");
                });

            modelBuilder.Entity("back.Entities.Asistencia", b =>
                {
                    b.HasOne("back.Entities.ClaseSesion", "ClaseSesion")
                        .WithMany("Asistencias")
                        .HasForeignKey("ClaseSesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Entities.User", "Estudiante")
                        .WithMany("AsistenciasEstudiante")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClaseSesion");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("back.Entities.Ayudantia", b =>
                {
                    b.HasOne("back.Entities.Catedra", "Catedra")
                        .WithMany("Ayudantias")
                        .HasForeignKey("CatedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Entities.User", "Estudiante")
                        .WithMany("AyudantiasEstudiante")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catedra");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("back.Entities.Bitacora", b =>
                {
                    b.HasOne("back.Entities.Ayudantia", "Ayudantia")
                        .WithMany("Bitacoras")
                        .HasForeignKey("AyudantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ayudantia");
                });

            modelBuilder.Entity("back.Entities.Catedra", b =>
                {
                    b.HasOne("back.Entities.User", "Docente")
                        .WithMany("CatedrasDocente")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("back.Entities.Clase", b =>
                {
                    b.HasOne("back.Entities.User", "Docente")
                        .WithMany("ClasesDocente")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Entities.Materia", "Materia")
                        .WithMany("Clases")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("back.Entities.ClaseSesion", b =>
                {
                    b.HasOne("back.Entities.Clase", "Clase")
                        .WithMany()
                        .HasForeignKey("ClaseId");

                    b.HasOne("back.Entities.User", "Docente")
                        .WithMany("ClasesSesionesDocente")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Entities.Materia", "Materia")
                        .WithMany("ClasesSesiones")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Docente");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("back.Entities.CronogramaActividad", b =>
                {
                    b.HasOne("back.Entities.Catedra", "Catedra")
                        .WithMany()
                        .HasForeignKey("CatedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catedra");
                });

            modelBuilder.Entity("back.Entities.Evaluacion", b =>
                {
                    b.HasOne("back.Entities.Catedra", "Catedra")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("CatedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catedra");
                });

            modelBuilder.Entity("back.Entities.ImportJob", b =>
                {
                    b.HasOne("back.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("back.Entities.ImportJobEntry", b =>
                {
                    b.HasOne("back.Entities.ImportJob", "ImportJob")
                        .WithMany("Entries")
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportJob");
                });

            modelBuilder.Entity("back.Entities.IndicadorCualitativo", b =>
                {
                    b.HasOne("back.Entities.Catedra", "Catedra")
                        .WithMany()
                        .HasForeignKey("CatedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Entities.User", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catedra");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("back.Entities.Inscripcion", b =>
                {
                    b.HasOne("back.Entities.Catedra", "Catedra")
                        .WithMany("Inscripciones")
                        .HasForeignKey("CatedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Entities.User", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catedra");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("back.Entities.Materia", b =>
                {
                    b.HasOne("back.Entities.User", "DocenteResponsable")
                        .WithMany()
                        .HasForeignKey("DocenteResponsableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocenteResponsable");
                });

            modelBuilder.Entity("back.Entities.Persona", b =>
                {
                    b.HasOne("back.Entities.User", "User")
                        .WithOne("Persona")
                        .HasForeignKey("back.Entities.Persona", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("back.Entities.Presentacion", b =>
                {
                    b.HasOne("back.Entities.Ayudantia", "Ayudantia")
                        .WithMany("Presentaciones")
                        .HasForeignKey("AyudantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Entities.User", "CoordinadorCarrera")
                        .WithMany()
                        .HasForeignKey("CoordinadorCarreraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("back.Entities.User", "Decano")
                        .WithMany()
                        .HasForeignKey("DecanoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ayudantia");

                    b.Navigation("CoordinadorCarrera");

                    b.Navigation("Decano");
                });

            modelBuilder.Entity("back.Entities.PresentacionEvaluacion", b =>
                {
                    b.HasOne("back.Entities.User", "Jurado")
                        .WithMany()
                        .HasForeignKey("JuradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Entities.Presentacion", "Presentacion")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("PresentacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jurado");

                    b.Navigation("Presentacion");
                });

            modelBuilder.Entity("back.Entities.Recurso", b =>
                {
                    b.HasOne("back.Entities.Materia", "Materia")
                        .WithMany("Recursos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("back.Entities.RecursoVistoPorEstudiante", b =>
                {
                    b.HasOne("back.Entities.User", "Estudiante")
                        .WithMany("RecursosVistos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Entities.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("back.Entities.Ayudantia", b =>
                {
                    b.Navigation("Bitacoras");

                    b.Navigation("Planificacion");

                    b.Navigation("Presentaciones");
                });

            modelBuilder.Entity("back.Entities.Catedra", b =>
                {
                    b.Navigation("Ayudantias");

                    b.Navigation("Evaluaciones");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("back.Entities.ClaseSesion", b =>
                {
                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("back.Entities.ImportJob", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("back.Entities.Materia", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Clases");

                    b.Navigation("ClasesSesiones");

                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("back.Entities.Presentacion", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("back.Entities.User", b =>
                {
                    b.Navigation("AsistenciasEstudiante");

                    b.Navigation("AyudantiasEstudiante");

                    b.Navigation("CatedrasDocente");

                    b.Navigation("ClasesDocente");

                    b.Navigation("ClasesSesionesDocente");

                    b.Navigation("Inscripciones");

                    b.Navigation("Persona")
                        .IsRequired();

                    b.Navigation("RecursosVistos");
                });
#pragma warning restore 612, 618
        }
    }
}
