// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back.Data;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809063454_AddPersonaAndRoles")]
    partial class AddPersonaAndRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("back.Entities.ActividadAyudantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AyudantiaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Completada")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPlanificada")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AyudantiaId");

                    b.ToTable("ActividadesAyudantia");
                });

            modelBuilder.Entity("back.Entities.Ayudantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatedraId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatedraId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Ayudantias");
                });

            modelBuilder.Entity("back.Entities.Bitacora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActividadesRealizadas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AyudantiaId")
                        .HasColumnType("integer");

                    b.Property<string>("EvidenciaUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AyudantiaId");

                    b.ToTable("Bitacoras");
                });

            modelBuilder.Entity("back.Entities.Catedra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.ToTable("Catedras");
                });

            modelBuilder.Entity("back.Entities.CronogramaActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatedraId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPrevista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaReal")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatedraId");

                    b.ToTable("Cronogramas");
                });

            modelBuilder.Entity("back.Entities.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdaptadaConIA")
                        .HasColumnType("boolean");

                    b.Property<int>("CatedraId")
                        .HasColumnType("integer");

                    b.Property<string>("DescripcionIA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsDiagnostica")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatedraId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("back.Entities.IndicadorCualitativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatedraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Indicador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatedraId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("IndicadoresCualitativos");
                });

            modelBuilder.Entity("back.Entities.Inscripcion", b =>
                {
                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<int>("CatedraId")
                        .HasColumnType("integer");

                    b.Property<bool>("AlertaRendimiento")
                        .HasColumnType("boolean");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<double>("PromedioActual")
                        .HasColumnType("double precision");

                    b.HasKey("EstudianteId", "CatedraId");

                    b.HasIndex("CatedraId");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("back.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("back.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("back.Entities.ActividadAyudantia", b =>
                {
                    b.HasOne("back.Entities.Ayudantia", "Ayudantia")
                        .WithMany("Planificacion")
                        .HasForeignKey("AyudantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ayudantia");
                });

            modelBuilder.Entity("back.Entities.Ayudantia", b =>
                {
                    b.HasOne("back.Entities.Catedra", "Catedra")
                        .WithMany("Ayudantias")
                        .HasForeignKey("CatedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Entities.User", "Estudiante")
                        .WithMany("AyudantiasEstudiante")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catedra");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("back.Entities.Bitacora", b =>
                {
                    b.HasOne("back.Entities.Ayudantia", "Ayudantia")
                        .WithMany("Bitacoras")
                        .HasForeignKey("AyudantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ayudantia");
                });

            modelBuilder.Entity("back.Entities.Catedra", b =>
                {
                    b.HasOne("back.Entities.User", "Docente")
                        .WithMany("CatedrasDocente")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("back.Entities.CronogramaActividad", b =>
                {
                    b.HasOne("back.Entities.Catedra", "Catedra")
                        .WithMany()
                        .HasForeignKey("CatedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catedra");
                });

            modelBuilder.Entity("back.Entities.Evaluacion", b =>
                {
                    b.HasOne("back.Entities.Catedra", "Catedra")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("CatedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catedra");
                });

            modelBuilder.Entity("back.Entities.IndicadorCualitativo", b =>
                {
                    b.HasOne("back.Entities.Catedra", "Catedra")
                        .WithMany()
                        .HasForeignKey("CatedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Entities.User", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catedra");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("back.Entities.Inscripcion", b =>
                {
                    b.HasOne("back.Entities.Catedra", "Catedra")
                        .WithMany("Inscripciones")
                        .HasForeignKey("CatedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Entities.User", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catedra");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("back.Entities.Persona", b =>
                {
                    b.HasOne("back.Entities.User", "User")
                        .WithOne("Persona")
                        .HasForeignKey("back.Entities.Persona", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("back.Entities.Ayudantia", b =>
                {
                    b.Navigation("Bitacoras");

                    b.Navigation("Planificacion");
                });

            modelBuilder.Entity("back.Entities.Catedra", b =>
                {
                    b.Navigation("Ayudantias");

                    b.Navigation("Evaluaciones");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("back.Entities.User", b =>
                {
                    b.Navigation("AyudantiasEstudiante");

                    b.Navigation("CatedrasDocente");

                    b.Navigation("Inscripciones");

                    b.Navigation("Persona")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
